# 数据库配置（自动使用HikariCP连接池）
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book_management?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 200391zcs#
    driver-class-name: com.mysql.cj.jdbc.Driver

# 服务器配置
server:
  port: 8082
  servlet:
    context-path: /book-management

# 日志配置
logging:
  level:
    com.zhouchangsheng: DEBUG
    org.springframework.jdbc: DEBUG

# swagger
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# jwt
jwt:
  expiration: 3600
  secret : 9UGTmceaFOEPabcili1KdL/FkaBjWZ/IvdTcpcAbqksl6ox0clrkJdja1cZ0/DCxgJMgnRcP52yg/p0bVkXVhA==
#  secret : "a8f3c7d9e2b4f6a1c0d5e8b7f9a3c2d6e4b1f7a9c8d0e5b3f6a2c7d9e4b8f1a0"
