# 数据库配置（自动使用HikariCP连接池）
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book_management?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 521137Server@@
    driver-class-name: com.mysql.cj.jdbc.Driver

# 服务器配置
server:
  port: 8082
  servlet:
    context-path: /book-management

# 日志配置
logging:
  level:
    com.zhouchangsheng: DEBUG
    org.springframework.jdbc: DEBUG

# swagger
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html